# Generated by Django 5.2.4 on 2025-07-31 06:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_landingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='content',
            field=wagtail.fields.StreamField([('char_block', 0), ('richtext_block', 1), ('text_block', 2), ('email_block', 3), ('url_block', 4)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.EmailBlock', (), {}), 4: ('wagtail.blocks.URLBlock', (), {})}, default=None, null=True),
        ),
    ]
