# Generated by Django 5.2.4 on 2025-07-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_landingpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='extra_title',
        ),
    ]
